// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7pnL1zDEliK1D6nzNNpstew4Aw1vkLns',
    appId: '1:1008160004128:web:4af658fd7131f8b9a30445',
    messagingSenderId: '1008160004128',
    projectId: 'projectjzn',
    authDomain: 'projectjzn.firebaseapp.com',
    storageBucket: 'projectjzn.firebasestorage.app',
    measurementId: 'G-WD5PKJ2SXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA1lpIlX1vCtZDzcqfKXHE8tlgRG5_v4Y',
    appId: '1:1008160004128:android:356b79d25e1be367a30445',
    messagingSenderId: '1008160004128',
    projectId: 'projectjzn',
    storageBucket: 'projectjzn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBLaVDbaSz5oJKb59zgcfOK2_PMRp7CQw',
    appId: '1:1008160004128:ios:54ae84d6d7df2535a30445',
    messagingSenderId: '1008160004128',
    projectId: 'projectjzn',
    storageBucket: 'projectjzn.firebasestorage.app',
    iosBundleId: 'com.example.joizoneApp',
  );
}
